image: node:0.10.30

cache:
    paths:
        - node_modules/

#all_tests:
#    script:
#        - npm install
#        - node index.js

pages:
    script:
        - npm install
        - node build-gitlab.js
        - mv build public
    artifacts:
        paths:
            - public
    #only:
    except:
        - master
