image: node:0.10.30

cache:
    paths:
        - node_modules/

services:

all_tests:
    script:
        - npm install
        - node index.js

pages:
    script:
        - node index.js
    artifacts:
        paths:
            - build
