image: node:0.10.30

cache:
    paths:
        - node_modules/

#all_tests:
#    script:
#        - npm install
#        - node index.js

pages:
    script:
        - npm install
        - node index.js
    artifacts:
        paths:
            - build
